import type { Exercise, MuscleGroup } from '../types';

export const EXERCISES: Exercise[] = [
  // ─── CHEST ────────────────────────────────────────────────
  {
    id: 'flat-barbell-bench',
    name: 'Flat Barbell Bench Press',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: 'Barbell',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: [
      'Lie flat on a bench, grip the bar slightly wider than shoulder-width.',
      'Unrack and lower the bar under control to mid-chest.',
      'Press explosively back to lockout.',
    ],
    tips: ['Keep shoulders retracted and depressed', 'Maintain a slight arch in your lower back', 'Drive your feet into the floor'],
  },
  {
    id: 'incline-db-press',
    name: 'Incline Dumbbell Press',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    equipment: 'Dumbbell',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: [
      'Set bench to 30-45°. Hold dumbbells at shoulder level.',
      'Press up and in, touching the heads at the top.',
      'Lower with control, elbows at ~75° from torso.',
    ],
    tips: ['Squeeze the upper chest at the top', 'Don\'t let the dumbbells drift too wide'],
  },
  {
    id: 'cable-crossover',
    name: 'Cable Crossover / Flye',
    muscleGroups: ['chest'],
    equipment: 'Cable Machine',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: [
      'Set cables at shoulder height. Stand centred, slight forward lean.',
      'Bring hands together in a wide arc in front of chest.',
      'Squeeze pecs and return under control.',
    ],
    tips: ['Maintain a slight bend in the elbows throughout', 'Think of hugging a tree'],
  },
  {
    id: 'push-up',
    name: 'Push Up',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: 'Bodyweight',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: [
      'Place hands shoulder-width apart, body in a straight line.',
      'Lower chest to floor, keeping core tight.',
      'Push back up to starting position.',
    ],
    tips: ['Don\'t let hips sag', 'Full range of motion for maximum benefit'],
  },
  {
    id: 'pec-deck',
    name: 'Pec Deck Machine',
    muscleGroups: ['chest'],
    equipment: 'Machine',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: [
      'Sit upright with elbows on the pads at 90°.',
      'Bring arms together squeezing the chest.',
      'Return slowly to the start position.',
    ],
    tips: ['Don\'t go too heavy — feel the stretch', 'Pause 1 second at peak contraction'],
  },
  {
    id: 'dips',
    name: 'Dips (Chest)',
    muscleGroups: ['chest', 'triceps'],
    equipment: 'Bodyweight',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: [
      'Grip parallel bars and lean slightly forward.',
      'Lower until upper arms are parallel to the floor.',
      'Push back up to lockout.',
    ],
    tips: ['Lean forward to emphasise chest', 'Add weight with a belt for progression'],
  },

  // ─── BACK ─────────────────────────────────────────────────
  {
    id: 'deadlift',
    name: 'Conventional Deadlift',
    muscleGroups: ['back', 'legs', 'glutes'],
    equipment: 'Barbell',
    mechanic: 'compound',
    difficulty: 'advanced',
    instructions: [
      'Stand with mid-foot under bar, hip-width stance.',
      'Hinge, grip just outside legs, brace core.',
      'Drive floor away, lock hips at the top.',
    ],
    tips: ['Bar stays in contact with legs throughout', 'Don\'t jerk — initiate the pull smoothly'],
  },
  {
    id: 'barbell-row',
    name: 'Barbell Bent-Over Row',
    muscleGroups: ['back', 'biceps'],
    equipment: 'Barbell',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: [
      'Hinge at hips to ~45°, grip bar shoulder-width.',
      'Row bar to lower chest, driving elbows back.',
      'Lower under control.',
    ],
    tips: ['Keep back flat, not rounded', 'Lead with the elbows not the hands'],
  },
  {
    id: 'pull-up',
    name: 'Pull-Up',
    muscleGroups: ['back', 'biceps'],
    equipment: 'Bodyweight',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: [
      'Grip bar slightly wider than shoulder-width, overhand.',
      'Pull chest to bar, driving elbows down.',
      'Lower fully and repeat.',
    ],
    tips: ['Full dead hang at the bottom for stretch', 'Depress shoulders before pulling'],
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    muscleGroups: ['back', 'biceps'],
    equipment: 'Cable Machine',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: [
      'Sit with thighs under pads, grip bar wide.',
      'Pull bar to upper chest, squeezing lats.',
      'Extend arms fully on the way up.',
    ],
    tips: ['Lean back slightly (~15°)', 'Think about pulling your elbows to your hips'],
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    muscleGroups: ['back', 'biceps'],
    equipment: 'Cable Machine',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: [
      'Sit upright with slight knee bend, grip the handle.',
      'Row handle to lower abdomen, squeeze shoulder blades.',
      'Extend arms with control.',
    ],
    tips: ['Don\'t round the lower back at the stretch', 'Keep chest up throughout'],
  },
  {
    id: 'face-pull',
    name: 'Face Pull',
    muscleGroups: ['shoulders', 'back'],
    equipment: 'Cable Machine',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: [
      'Set rope at eye level, grip with thumbs facing you.',
      'Pull to face, flaring elbows out.',
      'Rotate wrists back at the end.',
    ],
    tips: ['Great for shoulder health and rear delt development', 'Use light weight, high reps'],
  },
  {
    id: 't-bar-row',
    name: 'T-Bar Row',
    muscleGroups: ['back', 'biceps'],
    equipment: 'Barbell',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: [
      'Straddle the bar, hinge forward at hips.',
      'Grip the handle and row to chest.',
      'Lower with control.',
    ],
    tips: ['Keep back flat and parallel to floor', 'Squeeze hard at the top'],
  },

  // ─── SHOULDERS ────────────────────────────────────────────
  {
    id: 'overhead-press',
    name: 'Barbell Overhead Press',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'Barbell',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: [
      'Stand or sit, bar at collarbone height, grip shoulder-width.',
      'Press bar overhead to full lockout.',
      'Lower back to collar under control.',
    ],
    tips: ['Brace core like you\'re about to take a punch', 'Don\'t flare elbows too wide'],
  },
  {
    id: 'lateral-raise',
    name: 'Dumbbell Lateral Raise',
    muscleGroups: ['shoulders'],
    equipment: 'Dumbbell',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: [
      'Hold dumbbells at sides, slight bend in elbows.',
      'Raise arms to shoulder height, pinkies slightly higher.',
      'Lower slowly.',
    ],
    tips: ['Lead with the elbows not the hands', 'Slow eccentric (3-4 seconds) builds more muscle'],
  },
  {
    id: 'arnold-press',
    name: 'Arnold Press',
    muscleGroups: ['shoulders'],
    equipment: 'Dumbbell',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: [
      'Start with palms facing you, dumbbells at chin.',
      'Rotate palms out as you press overhead.',
      'Reverse the rotation on the way down.',
    ],
    tips: ['Hits all three deltoid heads', 'Controlled rotation is key'],
  },
  {
    id: 'rear-delt-flye',
    name: 'Rear Delt Flye',
    muscleGroups: ['shoulders', 'back'],
    equipment: 'Dumbbell',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: [
      'Hinge at hips or lie prone on incline bench.',
      'Raise dumbbells out to sides with straight arms.',
      'Squeeze rear delts at the top.',
    ],
    tips: ['Think of pouring water out of a jug', 'Avoid shrugging'],
  },

  // ─── BICEPS ───────────────────────────────────────────────
  {
    id: 'barbell-curl',
    name: 'Barbell Curl',
    muscleGroups: ['biceps'],
    equipment: 'Barbell',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: [
      'Stand with barbell at hip level, underhand grip.',
      'Curl bar to shoulders, keeping elbows at sides.',
      'Lower under control.',
    ],
    tips: ['Don\'t swing the torso', 'Squeeze at the top of the rep'],
  },
  {
    id: 'incline-db-curl',
    name: 'Incline Dumbbell Curl',
    muscleGroups: ['biceps'],
    equipment: 'Dumbbell',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: [
      'Sit back on incline bench, arms hang straight down.',
      'Curl both dumbbells up, supinating at the top.',
      'Lower all the way for full stretch.',
    ],
    tips: ['Provides a great stretch on the long head', 'Don\'t rush the negative'],
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    muscleGroups: ['biceps'],
    equipment: 'Dumbbell',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: [
      'Hold dumbbells with neutral (hammer) grip.',
      'Curl up keeping palms facing each other throughout.',
      'Lower with control.',
    ],
    tips: ['Builds the brachialis and brachioradialis', 'Can be done alternating or together'],
  },
  {
    id: 'preacher-curl',
    name: 'Preacher Curl',
    muscleGroups: ['biceps'],
    equipment: 'Barbell',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: [
      'Rest upper arms on preacher bench pad.',
      'Curl bar up, don\'t let arms flare.',
      'Lower fully for maximum stretch.',
    ],
    tips: ['Eliminates cheating — purely isolates the bicep', 'Use lighter weight than barbell curls'],
  },

  // ─── TRICEPS ──────────────────────────────────────────────
  {
    id: 'tricep-pushdown',
    name: 'Tricep Pushdown',
    muscleGroups: ['triceps'],
    equipment: 'Cable Machine',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: [
      'Grip bar with overhand grip, elbows at sides at ~90°.',
      'Push bar down to full elbow extension.',
      'Slowly return to start.',
    ],
    tips: ['Keep elbows tucked in throughout', 'Fully lock out on every rep'],
  },
  {
    id: 'skull-crusher',
    name: 'Skull Crusher (EZ Bar)',
    muscleGroups: ['triceps'],
    equipment: 'Barbell',
    mechanic: 'isolation',
    difficulty: 'intermediate',
    instructions: [
      'Lie on bench, hold EZ bar above chest with arms extended.',
      'Lower bar toward forehead, bending only at elbows.',
      'Extend back to start.',
    ],
    tips: ['Control the weight — no cheating', 'Move the elbows slightly back at the top for full stretch'],
  },
  {
    id: 'overhead-tricep-ext',
    name: 'Overhead Tricep Extension',
    muscleGroups: ['triceps'],
    equipment: 'Dumbbell',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: [
      'Hold one dumbbell overhead with both hands.',
      'Lower behind head by bending elbows.',
      'Extend arms back overhead.',
    ],
    tips: ['Stretches the long head maximally', 'Keep elbows pointing forward'],
  },
  {
    id: 'close-grip-bench',
    name: 'Close-Grip Bench Press',
    muscleGroups: ['triceps', 'chest'],
    equipment: 'Barbell',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: [
      'Grip bar shoulder-width or slightly narrower.',
      'Lower bar to chest, flare elbows only slightly.',
      'Press back to lockout.',
    ],
    tips: ['Heavier than isolation moves — great mass builder', 'Don\'t go too narrow — shoulder strain risk'],
  },

  // ─── LEGS ─────────────────────────────────────────────────
  {
    id: 'back-squat',
    name: 'Back Squat',
    muscleGroups: ['legs', 'glutes', 'core'],
    equipment: 'Barbell',
    mechanic: 'compound',
    difficulty: 'advanced',
    instructions: [
      'Bar on upper traps, stance shoulder-width, toes slightly out.',
      'Break at hips and knees simultaneously, descend until thighs are parallel.',
      'Drive through heels back to standing.',
    ],
    tips: ['Keep chest up and knees tracking over toes', 'Depth is king — don\'t cut it short'],
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    muscleGroups: ['legs', 'glutes'],
    equipment: 'Machine',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: [
      'Sit in leg press, feet shoulder-width on platform.',
      'Lower platform until knees are at 90°.',
      'Press to near lockout (don\'t lock knees).',
    ],
    tips: ['Foot placement affects muscle emphasis', 'Don\'t let the lower back curl off the pad'],
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    muscleGroups: ['legs', 'glutes', 'back'],
    equipment: 'Barbell',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: [
      'Stand holding bar, slight knee bend.',
      'Hinge at hips, sliding bar down legs until you feel a hamstring stretch.',
      'Drive hips forward to return to standing.',
    ],
    tips: ['Bar stays close to legs throughout', 'Stop at the bottom when back starts to round'],
  },
  {
    id: 'walking-lunge',
    name: 'Walking Lunge',
    muscleGroups: ['legs', 'glutes'],
    equipment: 'Dumbbell',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: [
      'Hold dumbbells at sides, step forward into lunge.',
      'Lower back knee toward floor.',
      'Drive off front foot and bring rear foot forward to repeat.',
    ],
    tips: ['Keep torso upright', 'Front knee stays behind toes'],
  },
  {
    id: 'leg-curl',
    name: 'Lying Leg Curl',
    muscleGroups: ['legs'],
    equipment: 'Machine',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: [
      'Lie face down on leg curl machine, pad against lower legs.',
      'Curl legs toward glutes.',
      'Lower under control without slamming the weight.',
    ],
    tips: ['Point toes slightly and internally rotate for more bicep femoris activation'],
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    muscleGroups: ['legs'],
    equipment: 'Machine',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: [
      'Sit on machine, pads on lower shins.',
      'Extend legs to full lockout.',
      'Lower slowly.',
    ],
    tips: ['Squeeze quads at the top', 'Don\'t use momentum — strict form'],
  },
  {
    id: 'front-squat',
    name: 'Front Squat',
    muscleGroups: ['legs', 'core'],
    equipment: 'Barbell',
    mechanic: 'compound',
    difficulty: 'advanced',
    instructions: [
      'Bar on front deltoids, elbows high, grip or clean position.',
      'Squat deep keeping torso very upright.',
      'Drive up through heels.',
    ],
    tips: ['More quad-dominant than back squat', 'Requires significant wrist and hip flexibility'],
  },
  {
    id: 'hack-squat',
    name: 'Hack Squat',
    muscleGroups: ['legs', 'glutes'],
    equipment: 'Machine',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: [
      'Position shoulders and back on the machine pads.',
      'Feet shoulder-width near the bottom of the platform.',
      'Lower until thighs are parallel, drive back up.',
    ],
    tips: ['Great alternative when lower back is fatigued from barbell work'],
  },

  // ─── GLUTES ───────────────────────────────────────────────
  {
    id: 'hip-thrust',
    name: 'Barbell Hip Thrust',
    muscleGroups: ['glutes', 'legs'],
    equipment: 'Barbell',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: [
      'Sit against a bench, bar across hips over a pad.',
      'Drive hips up to full extension, squeezing glutes.',
      'Lower under control.',
    ],
    tips: ['Top position: shins vertical, torso parallel to floor', 'Three-second squeeze at the top for max activation'],
  },
  {
    id: 'cable-kickback',
    name: 'Cable Glute Kickback',
    muscleGroups: ['glutes'],
    equipment: 'Cable Machine',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: [
      'Strap cable to ankle. Stand facing machine.',
      'Kick leg back and up, squeezing glute at extension.',
      'Return under control.',
    ],
    tips: ['Don\'t arch the lower back excessively', 'Keep the movement about hip extension not momentum'],
  },
  {
    id: 'sumo-deadlift',
    name: 'Sumo Deadlift',
    muscleGroups: ['glutes', 'legs', 'back'],
    equipment: 'Barbell',
    mechanic: 'compound',
    difficulty: 'advanced',
    instructions: [
      'Wide stance (1.5–2x shoulder-width), toes pointed 45° out.',
      'Grip bar inside the legs, brace core.',
      'Drive hips through at the top.',
    ],
    tips: ['More glute and inner thigh emphasis than conventional', 'Push the floor apart with your feet'],
  },

  // ─── CORE ─────────────────────────────────────────────────
  {
    id: 'plank',
    name: 'Plank',
    muscleGroups: ['core'],
    equipment: 'Bodyweight',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: [
      'Forearms on floor, elbows under shoulders.',
      'Keep body in straight line from head to heels.',
      'Hold the position, breathing steadily.',
    ],
    tips: ['Don\'t let hips sag or pike', 'Brace as if you\'re going to be hit in the stomach'],
  },
  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    muscleGroups: ['core'],
    equipment: 'Cable Machine',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: [
      'Kneel below a cable with rope attachment, gripped behind head.',
      'Crunch down rounding the spine.',
      'Return slowly.',
    ],
    tips: ['Don\'t pull with the arms — flex from the abs', 'Great for adding resistance to abs training'],
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    muscleGroups: ['core'],
    equipment: 'Bodyweight',
    mechanic: 'isolation',
    difficulty: 'intermediate',
    instructions: [
      'Hang from a pull-up bar.',
      'Raise legs to hip height (bent knee) or above (straight leg).',
      'Lower slowly, avoiding swing.',
    ],
    tips: ['Control the descent — don\'t swing', 'Posterior pelvic tilt at the top maximises lower ab activation'],
  },
  {
    id: 'ab-wheel',
    name: 'Ab Wheel Rollout',
    muscleGroups: ['core'],
    equipment: 'Minimal',
    mechanic: 'compound',
    difficulty: 'advanced',
    instructions: [
      'Kneel with ab wheel on floor in front.',
      'Roll forward keeping arms straight and back flat.',
      'Contract abs to pull wheel back.',
    ],
    tips: ['Start with shorter range and progress over time', 'Don\'t let lower back arch'],
  },

  // ─── CALVES ───────────────────────────────────────────────
  {
    id: 'standing-calf-raise',
    name: 'Standing Calf Raise',
    muscleGroups: ['calves'],
    equipment: 'Machine',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: [
      'Stand on the platform with shoulders under pads.',
      'Rise onto toes as high as possible.',
      'Lower heel fully below platform.',
    ],
    tips: ['Full range of motion is essential — don\'t bounce', 'Pause at top AND bottom for 1-2 seconds'],
  },
  {
    id: 'seated-calf-raise',
    name: 'Seated Calf Raise',
    muscleGroups: ['calves'],
    equipment: 'Machine',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: [
      'Sit with pad over lower thighs.',
      'Rise onto toes with soleus emphasis.',
      'Lower for full stretch.',
    ],
    tips: ['Targets soleus (deeper calf muscle) unlike standing variations'],
  },

  // ─── CARDIO / FULL-BODY ───────────────────────────────────
  {
    id: 'burpee',
    name: 'Burpee',
    muscleGroups: ['legs', 'chest', 'core'],
    equipment: 'Bodyweight',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: [
      'Stand, drop hands to floor, jump feet back to push-up position.',
      'Perform a push-up.',
      'Jump feet forward and jump vertically.',
    ],
    tips: ['Pace yourself — they are taxing', 'Can modify by stepping instead of jumping'],
  },
  {
    id: 'box-jump',
    name: 'Box Jump',
    muscleGroups: ['legs', 'glutes'],
    equipment: 'Minimal',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: [
      'Stand in front of box, arms back.',
      'Swing arms and jump onto box, landing softly.',
      'Step down and reset.',
    ],
    tips: ['Land with knees bent, hip-width stance', 'Step down rather than jumping down to protect knees'],
  },
  {
    id: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    muscleGroups: ['glutes', 'back', 'legs'],
    equipment: 'Minimal',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: [
      'Stand with kettlebell between feet, hinge at hips.',
      'Hike KB back, then explosively drive hips forward.',
      'Let KB float to chest height, then control it back.',
    ],
    tips: ['It\'s a hip hinge — not a squat', 'Power comes from the glutes not the arms'],
  },
  {
    id: 'mountain-climber',
    name: 'Mountain Climber',
    muscleGroups: ['core', 'legs'],
    equipment: 'Bodyweight',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: [
      'Start in push-up position.',
      'Alternate driving knees to chest rapidly.',
      'Keep hips level throughout.',
    ],
    tips: ['Faster = more cardio, slower = more core', 'Don\'t let hips pike up'],
  },
  {
    id: 'treadmill-sprint',
    name: 'Sprint Interval',
    muscleGroups: ['legs', 'glutes'],
    equipment: 'Cardio Equipment',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: [
      'Set treadmill to high speed (12–18 km/h).',
      'Sprint for 20-30 seconds at max effort.',
      'Rest for 30-60 seconds and repeat.',
    ],
    tips: ['Hold on lightly or go belt-free', 'Best done 6-10 rounds'],
  },

  // ─── FULL-BODY COMPOUNDS ──────────────────────────────────
  {
    id: 'power-clean',
    name: 'Power Clean',
    muscleGroups: ['back', 'legs', 'shoulders'],
    equipment: 'Barbell',
    mechanic: 'compound',
    difficulty: 'advanced',
    instructions: [
      'Pull bar from floor explosively.',
      'Extend hips and shrug, pulling elbows under the bar.',
      'Catch in a quarter squat.',
    ],
    tips: ['Requires coaching if new — high injury risk without technique', 'Speed off the floor is key'],
  },
  {
    id: 'thruster',
    name: 'Thruster',
    muscleGroups: ['legs', 'shoulders', 'core'],
    equipment: 'Barbell',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: [
      'Front-rack position, perform a front squat.',
      'As you rise from the squat, press the bar overhead.',
      'Lower to front rack and repeat.',
    ],
    tips: ['Use the momentum from the squat to initiate the press', 'Great conditioning tool'],
  },
  {
    id: 'farmers-carry',
    name: 'Farmer\'s Carry',
    muscleGroups: ['core', 'back', 'legs'],
    equipment: 'Dumbbell',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: [
      'Pick up heavy dumbbells or kettlebells.',
      'Walk 20-40 meters with perfect posture.',
      'Set down and rest briefly.',
    ],
    tips: ['Squeeze handles as hard as possible', 'Builds grip strength and core stability'],
  },

  // ─── ADDITIONAL EXERCISES ─────────────────────────────────
  {
    id: 'goblet-squat',
    name: 'Goblet Squat',
    muscleGroups: ['legs', 'glutes', 'core'],
    equipment: 'Dumbbell',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: [
      'Hold a dumbbell vertically at chest height.',
      'Squat deep keeping elbows inside the knees.',
      'Return to standing.',
    ],
    tips: ['Great for learning squat mechanics', 'Use elbows to push knees out at the bottom'],
  },
  {
    id: 'step-up',
    name: 'Dumbbell Step-Up',
    muscleGroups: ['legs', 'glutes'],
    equipment: 'Dumbbell',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: [
      'Hold dumbbells at sides, step up onto bench or box.',
      'Drive through the heel of the elevated leg.',
      'Step down and alternate.',
    ],
    tips: ['Don\'t push off with the trailing foot', 'Great unilateral lower-body developer'],
  },
  {
    id: 'single-leg-rdl',
    name: 'Single-Leg RDL',
    muscleGroups: ['legs', 'glutes'],
    equipment: 'Dumbbell',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: [
      'Stand on one foot, hold dumbbell in opposite hand.',
      'Hinge and reach forward until torso is parallel to floor.',
      'Return to standing, squeezing the glute.',
    ],
    tips: ['Keep hips square throughout', 'Powerful for glute-ham development and balance'],
  },
  {
    id: 'nordic-curl',
    name: 'Nordic Hamstring Curl',
    muscleGroups: ['legs'],
    equipment: 'Bodyweight',
    mechanic: 'isolation',
    difficulty: 'advanced',
    instructions: [
      'Secure feet under a fixed bar, kneel upright.',
      'Lower body toward floor as slowly as possible.',
      'Use hands to push back up and repeat.',
    ],
    tips: ['One of the most effective hamstring exercises', 'Extremely eccentric-heavy — start with partial range'],
  },
  {
    id: 'chest-supported-row',
    name: 'Chest-Supported Row',
    muscleGroups: ['back', 'biceps'],
    equipment: 'Dumbbell',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: [
      'Lie face down on incline bench, hold dumbbells.',
      'Row dumbbells up, driving elbows back.',
      'Lower with control.',
    ],
    tips: ['Chest support eliminates lower back fatigue', 'Focus entirely on the back contraction'],
  },
  {
    id: 'zottman-curl',
    name: 'Zottman Curl',
    muscleGroups: ['biceps'],
    equipment: 'Dumbbell',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: [
      'Curl dumbbells up with a supinated grip.',
      'At the top, rotate to a pronated grip.',
      'Lower slowly and rotate back at the bottom.',
    ],
    tips: ['Trains both bicep and brachioradialis in one mov', 'Control the negative for maximum effect'],
  },
];

export const MUSCLE_GROUPS: MuscleGroup[] = ['chest', 'back', 'shoulders', 'biceps', 'triceps', 'legs', 'glutes', 'core', 'calves'];
export const EQUIPMENT_TYPES = ['Barbell', 'Dumbbell', 'Cable Machine', 'Machine', 'Bodyweight', 'Minimal', 'Cardio Equipment'];
export const DIFFICULTY_LEVELS = ['beginner', 'intermediate', 'advanced'] as const;
